title: "Appointment Booking System Project"
description: "A comprehensive cloud technologies project using Cal.com"
baseurl: ""
url: "https://thaiha-hub.github.io/your-repo-name"

# Theme
theme: minima
# Or use remote theme for more options:
# remote_theme: pages-themes/cayman@v0.2.0

# Navigation
header_pages:
  - docs/planning.md
  - docs/implementation.md
  - docs/optimization.md
  - docs/reflection.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown processor
markdown: kramdown
highlighter: rouge

# Custom variables
author: "Thai Ha Dang"
course: "DevOps Engineering - Molnteknologier 2025"
semester: "Vår 2025"
